<?php

namespace Tests\Feature;

use Corals\Modules\Entity\Models\Entity;
use Corals\Modules\Entity\Models\Entry;
use Corals\User\Models\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\Auth;
use Tests\TestCase;

class EntriesTest extends TestCase
{
    use DatabaseTransactions;

    protected $entity;
    protected $entry;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $user = User::query()->whereHas('roles', function ($query) {
            $query->where('name', 'superuser');
        })->first();
        Auth::loginUsingId($user->id);
    }

    public function test_entities_store()
    {
        $types = get_array_key_translation(config("settings.models.custom_field_setting.supported_types"));
        $type = array_rand($types);
        $code = uniqid('entity-');
        $response = $this->post(
            'entity/entities',
            [
                'code' => $code,
                'name_singular' => 'entity singular',
                'name_plural' => 'entities',
                'fields' => [
                    [
                        'name' => 'field name',
                        'type' => $type,
                        'status' => 'active',
                        "field_config" => [
                            "is_identifier" => "on",
                        ],
                        "label" => 'field',
                    ],
                ],
            ]
        );

        $this->entity = Entity::query()->where('code', $code)->first();

        $response->assertDontSee('The given data was invalid')
            ->assertRedirect('entity/entities');

        $this->assertDatabaseHas('entity_entities', [
            'code' => $this->entity->code,
            'name_singular' => $this->entity->name_singular,
            'name_plural' => $this->entity->name_plural,
        ]);
    }

    public function test_entries_store()
    {
        $this->test_entities_store();

        if ($this->entity) {
            $response = $this->post('entity/entities/' . $this->entity->hashed_id.'/entries', [
                'properties' => [
                    $this->entity->fields[0]['name'] => 'entry',
            ],
            ]);

            $this->entry = Entry::query()->where('entity_id', $this->entity->id)->first();

            $response->assertDontSee('The given data was invalid')
                ->assertRedirect('entity/entities/' . $this->entity->hashed_id.'/entries');

            $this->assertDatabaseHas('entity_entries', [
                'entity_id' => $this->entity->id,
            ]);
        }
    }

    public function test_entries_show()
    {
        $this->test_entries_store();

        if ($this->entry) {
            $response = $this->get('entity/entities/' . $this->entity->hashed_id.'/entries/'.$this->entry->hashed_id);

            $response->assertViewIs('Entity::entries.show')->assertStatus(200);
        }
        $this->assertTrue(true);
    }

    public function test_entries_edit()
    {
        $this->test_entries_store();

        if ($this->entry) {
            $response = $this->get('entity/entities/' . $this->entity->hashed_id.'/entries/'.$this->entry->hashed_id.'/edit');

            $response->assertValid('Entity::entries.create_edit');
        }
        $this->assertTrue(true);
    }

    public function test_entries_update()
    {
        $this->test_entries_store();

        if ($this->entry) {
            $response = $this->put('entity/entities/' . $this->entity->hashed_id.'/entries/'.$this->entry->hashed_id, [
                'properties' => [
                    $this->entity->fields[0]['name'] => 'entry',
                ],
            ]);

            $response->assertDontSee('The given data was invalid')
                ->assertRedirect('entity/entities/' . $this->entity->hashed_id.'/entries');
        }
        $this->assertTrue(true);
    }

    public function test_entries_delete()
    {
        $this->test_entries_store();

        if ($this->entry) {
            $response = $this->delete('entity/entities/' . $this->entity->hashed_id.'/entries/'.$this->entry->hashed_id);

            $this->isSoftDeletableModel(Entry::class);
            $response->assertStatus(200)->assertSeeText('entry has been deleted successfully.');
        }
        $this->assertTrue(true);
    }
}
